version: '3.1'

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: dev
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_username
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
    command: mongod
    secrets:
      - mongodb_password
      - mongodb_username

secrets:
  mongodb_password:
    file: ./credentials/.mongodb_password
  mongodb_username:
    file: ./credentials/.mongodb_username